# Generated by Django 4.1 on 2023-11-15 22:13

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Estacao",
            fields=[
                (
                    "station",
                    models.CharField(max_length=200, primary_key=True, serialize=False),
                ),
                ("station_number", models.IntegerField()),
                ("station_name", models.CharField(max_length=200)),
                ("lat", models.FloatField()),
                ("lon", models.FloatField()),
            ],
            options={
                "db_table": "df_stations",
            },
        ),
        migrations.CreateModel(
            name="RidesMesclado",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_gender", models.CharField(max_length=10)),
                ("user_birthdate", models.DateField()),
                ("user_residence", models.CharField(max_length=255)),
                ("ride_date", models.DateField()),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("station_start", models.CharField(max_length=255)),
                ("station_end", models.CharField(max_length=255)),
                ("ride_duration", models.DurationField()),
                ("ride_late", models.BooleanField()),
                ("station_start_lat", models.FloatField()),
                ("station_start_lon", models.FloatField()),
                ("station_end_lat", models.FloatField()),
                ("station_end_lon", models.FloatField()),
            ],
            options={
                "db_table": "rides_mesclado",
            },
        ),
    ]
