# Generated by Django 4.1 on 2023-11-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apimapa", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Corrida",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("user_gender", models.CharField(max_length=10)),
                ("user_birthdate", models.DateField()),
                ("user_residence", models.CharField(max_length=255)),
                ("ride_date", models.DateField()),
                ("time_start", models.TimeField()),
                ("time_end", models.TimeField()),
                ("station_start", models.CharField(max_length=255)),
                ("station_end", models.CharField(max_length=255)),
                ("ride_duration", models.FloatField()),
                ("ride_late", models.BooleanField()),
                ("station_start_lat", models.FloatField()),
                ("station_start_lon", models.FloatField()),
                ("station_end_lat", models.FloatField()),
                ("station_end_lon", models.FloatField()),
            ],
        ),
        migrations.AlterField(
            model_name="ridesmesclado",
            name="ride_duration",
            field=models.FloatField(),
        ),
    ]
